# Generated by Django 3.2.9 on 2021-11-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('posts', '0012_post_make_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
